### ISSUE TITLE
ローカル住所データベースを使用した2回目以降のリバースジオコーディングに失敗する

### ISSUE THREAD

**Issue by yonaka** [t-sagara/jageocoder#32]
いつもお世話になっております。

　2.1.7でリバースジオコーディングしようとすると、以下のようなエラーになり失敗します。
　install-dictionary後初回のreverse時にインデックスが生成されるようですが、このときだけは成功します。2回目以降がダメなようです。

```
(venv) PS C:\work\Project\GpmfDataTelop\GeoTelop> jageocoder uninstall-dictionary
INFO:jageocoder.module:285:uninstall_dictionary:Removing directory C:\work\Project\GpmfDataTelop\GeoTelop\venv\jageocoder\db2
INFO:jageocoder.module:288:uninstall_dictionary:Dictionary has been uninstalled.
(venv) PS C:\work\Project\GpmfDataTelop\GeoTelop> jageocoder download-dictionary https://www.info-proto.com/static/jageocoder/20240429/v2/jukyo_all_v21.zip
INFO:jageocoder.module:209:download_dictionary:Downloading zipped dictionary file from https://www.info-proto.com/static/jageocoder/20240429/v2/jukyo_all_v21.zip to C:\work\Project\GpmfDataTelop\GeoTelop\jukyo_all_v21.zip
INFO:jageocoder.module:213:download_dictionary:.. download complete.
(venv) PS C:\work\Project\GpmfDataTelop\GeoTelop> jageocoder install-dictionary jukyo_all_v21.zip
INFO:jageocoder.module:263:install_dictionary:Please read 'C:\work\Project\GpmfDataTelop\GeoTelop\venv\jageocoder\db2\README.md' for terms and conditions of use.
INFO:jageocoder.module:267:install_dictionary:Installation completed.
(venv) PS C:\work\Project\GpmfDataTelop\GeoTelop> jageocoder reverse 139.691778 35.689627
INFO:jageocoder.rtree:325:create_rtree:Building RTree for reverse geocoding...
100%|##############################################################9| 263903206/263903207 [3:17:25<00:00, 22279.25it/s]
[{"candidate": {"id": 80217770, "name": "二丁目", "x": 139.6917724609375, "y": 35.689449310302734, "level": 6, "priority": 2, "note": "aza_id:0023002/postcode:1600023", "fullname": ["東京都", "新宿区", "西新宿", "二丁目"]}, "dist": 0.5319128710637626}]
(venv) PS C:\work\Project\GpmfDataTelop\GeoTelop> jageocoder reverse 139.691778 35.689627
WARNING:jageocoder.rtree:264:__init__:RTree datafile exists but it does not match the registered address data.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\work\Project\GpmfDataTelop\GeoTelop\venv\Scripts\jageocoder.exe\__main__.py", line 7, in <module>
  File "C:\work\Project\GpmfDataTelop\GeoTelop\venv\Lib\site-packages\jageocoder\__main__.py", line 126, in main
    jageocoder.reverse(
  File "C:\work\Project\GpmfDataTelop\GeoTelop\venv\Lib\site-packages\jageocoder\module.py", line 491, in reverse
    return _tree.reverse(x, y, level, as_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\Project\GpmfDataTelop\GeoTelop\venv\Lib\site-packages\jageocoder\tree.py", line 1168, in reverse
    self.reverse_index = Index(tree=self)
                         ^^^^^^^^^^^^^^^^
  File "C:\work\Project\GpmfDataTelop\GeoTelop\venv\Lib\site-packages\jageocoder\rtree.py", line 268, in __init__
    os.unlink(treepath + ".dat")
PermissionError: [WinError 32] プロセスはファイルにアクセスできません。別のプロセスが使用中です。: 'C:\\work\\Project\\GpmfDataTelop\\GeoTelop\\venv\\jageocoder\\db2\\rtree.dat'
```
　「RTree datafile exists but it does not match the registered address data.」はWarningのようなので、そのあとに出ている「PermissionError: [WinError 32] **プロセスはファイルにアクセスできません。別のプロセスが使用中です。」の方が真の問題なのかも知れません。

　OSはWindows 11で、WindowsストアのPythonを入れています。
```
(venv) PS C:\work\Project\GpmfDataTelop\GeoTelop> jageocoder -v
2.1.7
(venv) PS C:\work\Project\GpmfDataTelop\GeoTelop> python --version
Python 3.11.9

```

**Comment by t-sagara** [comment]
@yonaka ご指摘ありがとうございます。こちらでも同じ問題を確認しました。
修正したバージョンを v2.1.7.post1 として登録しましたので、更新してお試しください。
長時間かかるインデックスの作成を何度も実行させてしまい、ご不便をおかけします。
```
(.venv) PS C:\Users\sagara\Documents\github\jageocoder> pip install jageocoder==2.1.7.post1
Requirement already satisfied: jageocoder==2.1.7.post1 in ...
...
(.venv) PS C:\Users\sagara\Documents\github\jageocoder> jageocoder reverse 139.691778 35.689627
[{"candidate": {"id": 80217770, "name": "二丁目", "x": 139.6917724609375, "y": 35.689449310302734, "level": 6, "priority": 2, "note": "aza_id:0023002/postcode:1600023", "fullname": ["東京都", "新宿区", "西新宿", "二丁目"]}, "dist": 0.5319128710637626}]
```

**Comment by yonaka** [comment]
早速の対応ありがとうございます。
v2.1.7.post1で問題が解消されていることを確認しました。

**Comment by t-sagara** [comment]
@yonaka ご確認ありがとうございます。こちらは Close いたします。
